### ISSUE TITLE
Can't get my powerstrip with 2 outlets on it to work......

### ISSUE THREAD

**Issue by ldhall1856** [drumfreak/homebridge-tuya-powerstrip#2]
I've gotten the device ID and IP address and the localkey but still can't get it to work.

Here is my config.json

{
		"accessory": "TuyaPowerStrip",
		"name": "Outside Outlets",
		"description": "Tuya Power Strip Outlet 1",
		"ip": "192.168.3.124",
		"devId": "03200209dc4f2xxxxxxx”,
		"localKey": "ebc20793cxxxxxxx”,
		"dps": 2,
		"apiMinTimeout": 100,
		"apiMaxTimeout": 1000,
		"apiRetries": 1,
		"apiDebug": false,
		"refreshInterval": 120,
		"debugPrefix": "~~~!~~~ ",
		"debug": false,
		"deviceEnabled": true
	}],

**Comment by drumfreak** [comment]
You'll need to set 2 different outlets for the strip if it has 2 outlets. The dps value is the outlet number from the api, so you'll have to be aware of which outlet you're controlling. Add a second one, or even a third one with dps values 1, 2, 3 and test to see which one controls which outlet. 

```
[{
"accessory": "TuyaPowerStrip",
"name": "Outlet1",
"description": "Oulet1",
"ip": "192.168.3.124",
"devId": "03200209dc4f2xxxxxxx”,
"localKey": "ebc20793cxxxxxxx”,
"dps": 1,
"apiMinTimeout": 100,
"apiMaxTimeout": 1000,
"apiRetries": 1,
"apiDebug": false,
"refreshInterval": 120,
"debugPrefix": "~~~!~~~ ",
"debug": false,
"deviceEnabled": true
},
{ "accessory": "TuyaPowerStrip",
"name": "Outlet2",
"description": "Outlet2",
"ip": "192.168.3.124",
"devId": "03200209dc4f2xxxxxxx”,
"localKey": "ebc20793cxxxxxxx”,
"dps": 2,
"apiMinTimeout": 100,
"apiMaxTimeout": 1000,
"apiRetries": 1,
"apiDebug": false,
"refreshInterval": 120,
"debugPrefix": "~~~!~~~ ",
"debug": false,
"deviceEnabled": true
},
{
"accessory": "TuyaPowerStrip",
"name": "Outlet3",
"description": "Outlet3",
"ip": "192.168.3.124",
"devId": "03200209dc4f2xxxxxxx”,
"localKey": "ebc20793cxxxxxxx”,
"dps": 3,
"apiMinTimeout": 3000,
"apiMaxTimeout": 20000,
"apiRetries": 5,
"apiDebug": false,
"refreshInterval": 120,
"debugPrefix": "~~~!~~~ ",
"debug": true,
"superDebug": true,
"deviceEnabled": true
}]
```

**First, before you apply the above config, just delete the old power strip accessories and restart homebridge to flush out and remove the old outlet. Then, add the above to your new config, replacing the XXX's with your values, and then save and start homebridge.** 

- In the above config, I changed the dps value of the first item which was your config to 1. 

- I added 2 more outlets to potentially cover the 2nd outlet and the master power switch (they have an extra dps (device function point) value for the overall powerstrip... it's usually the number of outlets + 1. 

- I enabled debug (and undocumented superDebug) in item 3 so you can watch the journalctl -f -u homebridge and see the output from the log file, it's very descriptive. 

- on the 3rd outlet above, I set the api retries to 5, the timeout much higher since you labeled them "outside" outlets. Sometimes these really low api settings for default are meant for strong wifi signal inside, so on exterior items, or with slightly out of wifi range, tweaking those values helps ensure a connection is allowed before reporting back with no response. The better the wifi connection, the quicker your devices refresh in homebridge and homekit also, so this is of concern should devices not function when you have an automation setup, so tweak the api timeouts and retries up (slightly) until it works for you.  


>> Also note: The time of day, sun rays, alignment of the planets (is Mercury in retrograde or not?), depending on the wind and barometric pressure, in accordance with the moon phase and magnetic pull, any potential microwave or other signal interference, including human interference consisting of bad moods, angry attitudes, negative vibrations, bad intentions, unobserved thoughts from the perspective of awareness, misaligned intentions, crappy behaviors, and or malformed words misusing language can affect wifi your signal and effect your ability to toggle power switches. In other words, be a good person around your wifi network, and all will be well, with the above settings and a good attitude.

(I was bored...).

Please also make sure you're on the latest version:

`npm -i homebridge-tuya-powerstrip`

or if you do global installs:

`sudo npm -i -g homebridge-tuya-powerstrip`

Let me know how it goes!

**Comment by ldhall1856** [comment]
I think this will probably work, but i'm having a hard time getting my json file to work...

Maybe i'm missing something but i can't get it.
<img width="1244" alt="screen shot 2018-04-18 at 10 45 57 am" src="https://user-images.githubusercontent.com/37450359/38943126-3de95ede-42f6-11e8-97af-2d22b0dfb062.png">

**Comment by drumfreak** [comment]
Hmmm... can you post the whole config? Please sanitize it first.

**Comment by ldhall1856** [comment]
So.... I was making a dumb mistake..... I fixed that and its not working!  But overall it has made my homekit slower....  Also, Is there a way to have a over all power off and on? I have only 2 outlets.   With my other single outlets i was using TuyaOutlet and it never gave me the status update in my command prompt... I feel like that has a lot to do with making it slower....  but i might be wrong.....

anyway to fix


{
		"accessory": "TuyaPowerStrip",
		"name": "Outlet1",
		"description": "Oulet1",
		"ip": "192.168.3.124",
		"devId": "03200209dc4f228463e7",
		"localKey": "ebc20793c9224a87",
		"dps": 1,
		"apiMinTimeout": 100,
		"apiMaxTimeout": 1000,
		"apiRetries": 1,
		"apiDebug": false,
		"refreshInterval": 120,
		"debugPrefix": "~~~!~~~ ",
		"debug": false,
		"deviceEnabled": true
	}, {
		"accessory": "TuyaPowerStrip",
		"name": "Outlet2",
		"description": "Outlet2",
		"ip": "192.168.3.124",
		"devId": "03200209dc4f228463e7",
		"localKey": "ebc20793c9224a87",
		"dps": 2,
		"apiMinTimeout": 100,
		"apiMaxTimeout": 1000,
		"apiRetries": 1,
		"apiDebug": false,
		"refreshInterval": 120,
		"debugPrefix": "~~~!~~~ ",
		"debug": false,
		"deviceEnabled": true
	}, {
		"accessory": "TuyaPowerStrip",
		"name": "Outlet3",
		"description": "Outlet3",
		"ip": "192.168.3.124",
		"devId": "03200209dc4f228463e7",
		"localKey": "ebc20793c9224a87",
		"dps": 3,
		"apiMinTimeout": 3000,
		"apiMaxTimeout": 20000,
		"apiRetries": 5,
		"apiDebug": false,
		"refreshInterval": 120,
		"debugPrefix": "~~~!~~~ ",
		"debug": true,
		"superDebug": true,
		"deviceEnabled": true



<img width="547" alt="screen shot 2018-04-19 at 9 03 18 am" src="https://user-images.githubusercontent.com/37450359/38996579-1ee954d8-43b1-11e8-800d-4a6769e1b12d.png">

**Comment by ldhall1856** [comment]
It is also interrupting my garage door opener which is using the assurelink2 homebridge plug-in.  It wouldn't allow it to update. Kept telling me it was open when it was shut and wouldn't allow me to control it.

**Comment by iot07733** [comment]
Hi - great plugin!  I got one power strip to work, but trying to add second one does not work. I can control both from app.  this is the error i get.

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 3cf2ba4e-2343-4fd5-a93b-b4caf06301e3
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:279:18)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

thoughts?  or does this mean i need to set up another home bridge??

thanks

**Comment by drumfreak** [comment]
Each accessory must have a unique name in this version. Try that and let me know!

**Comment by iot07733** [comment]
yes - thanks! i figured that out after starting a second homebridge with only that device and got the same error— copy and paste error

works great

**Comment by drumfreak** [comment]
maybe you can delete the accessories/ cache and persist files and try again on the main homebridge with unique names. That’s all that happened, I’m going to turn this into a platform soon to manage that.

**Comment by huschpuscheli** [comment]
i have s similar problem, i think. i managed to get all 4 outlets, plus the usb outlet to work. but unfortunately, i cannot get the master switch to work. also i don't know how so tinker with the dps since i don't understand how to use "journalctl -f -u homebridge". this is my config for the outlet:
`"accessories": [


		{
			"accessory": "TuyaPowerStrip",
			"name": "Master?!",
			"description": "Master?",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 0,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Subwoofer",
			"description": "Subwoofer",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 1,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Drucker",
			"description": "Drucker",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 2,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Lüfter",
			"description": "Lüfter",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 3,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "TV",
			"description": "TV",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 4,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},

		{
			"accessory": "TuyaPowerStrip",
			"name": "USB",
			"description": "USB",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 7,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		}
	]`

it would be wonderful if you could help me. thank you in advance :)

**Comment by huschpuscheli** [comment]
i have s similar problem, i think. i managed to get all 4 outlets, plus the usb outlet to work. but unfortunately, i cannot get the master switch to work. also i don't know how so tinker with the dps since i don't understand how to use "journalctl -f -u homebridge". this is my config for the outlets:

`[


		{
			"accessory": "TuyaPowerStrip",
			"name": "Master?!",
			"description": "Master?",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 0,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Subwoofer",
			"description": "Subwoofer",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 1,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Drucker",
			"description": "Drucker",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 2,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Lüfter",
			"description": "Lüfter",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 3,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "TV",
			"description": "TV",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 4,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},

		{
			"accessory": "TuyaPowerStrip",
			"name": "USB",
			"description": "USB",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 7,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		}
	]`
it would be wonderful if you could help me. thank you in advance.

**Comment by huschpuscheli** [comment]
i have s similar problem, i think. i managed to get all 4 outlets, plus the usb outlet to work. but unfortunately, i cannot get the master switch to work. also i don't know how so tinker with the dps since i don't understand how to use "journalctl -f -u homebridge". this is my config for the outlets:
`{
"accessory": "TuyaPowerStrip",
"name": "Master?!",
"description": "Master?",
"ip": "192.168.178.200",
"devId": "17007751600194afc8de",
"localKey": "d2c2512966953903",
"dps": 0,
"apiMinTimeout": 100,
"apiMaxTimeout": 1000,
"apiRetries": 1,
"apiDebug": false,
"refreshInterval": 120,
"debugPrefix": "~~~!~~~ ",
"debug": true,
"superDebug": true,
"deviceEnabled": true
},
{
"accessory": "TuyaPowerStrip",
"name": "Subwoofer",
"description": "Subwoofer",
"ip": "192.168.178.200",
"devId": "17007751600194afc8de",
"localKey": "d2c2512966953903",
"dps": 1,
"apiMinTimeout": 100,
"apiMaxTimeout": 1000,
"apiRetries": 1,
"apiDebug": false,
"refreshInterval": 120,
"debugPrefix": "~~~!~~~ ",
"debug": true,
"superDebug": true,
"deviceEnabled": true
},
{
"accessory": "TuyaPowerStrip",
"name": "Drucker",
"description": "Drucker",
"ip": "192.168.178.200",
"devId": "17007751600194afc8de",
"localKey": "d2c2512966953903",
"dps": 2,
"apiMinTimeout": 100,
"apiMaxTimeout": 1000,
"apiRetries": 1,
"apiDebug": false,
"refreshInterval": 120,
"debugPrefix": "~~~!~~~ ",
"debug": true,
"superDebug": true,
"deviceEnabled": true
},
{
"accessory": "TuyaPowerStrip",
"name": "Lüfter",
"description": "Lüfter",
"ip": "192.168.178.200",
"devId": "17007751600194afc8de",
"localKey": "d2c2512966953903",
"dps": 3,
"apiMinTimeout": 100,
"apiMaxTimeout": 1000,
"apiRetries": 1,
"apiDebug": false,
"refreshInterval": 120,
"debugPrefix": "~~~!~~~ ",
"debug": true,
"superDebug": true,
"deviceEnabled": true
},
{
"accessory": "TuyaPowerStrip",
"name": "TV",
"description": "TV",
"ip": "192.168.178.200",
"devId": "17007751600194afc8de",
"localKey": "d2c2512966953903",
"dps": 4,
"apiMinTimeout": 100,
"apiMaxTimeout": 1000,
"apiRetries": 1,
"apiDebug": false,
"refreshInterval": 120,
"debugPrefix": "~~~!~~~ ",
"debug": true,
"superDebug": true,
"deviceEnabled": true
},
{
"accessory": "TuyaPowerStrip",
"name": "USB",
"description": "USB",
"ip": "192.168.178.200",
"devId": "17007751600194afc8de",
"localKey": "d2c2512966953903",
"dps": 7,
"apiMinTimeout": 100,
"apiMaxTimeout": 1000,
"apiRetries": 1,
"apiDebug": false,
"refreshInterval": 120,
"debugPrefix": "~~~!~~~ ",
"debug": true,
"superDebug": true,
"deviceEnabled": true
}`
it would be wonderful if you could help me. thank you in advance.

**Comment by huschpuscheli** [comment]
`[
		{
			"accessory": "TuyaPowerStrip",
			"name": "Master?!",
			"description": "Master?",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 0,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Subwoofer",
			"description": "Subwoofer",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 1,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Drucker",
			"description": "Drucker",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 2,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Lüfter",
			"description": "Lüfter",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 3,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "TV",
			"description": "TV",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 4,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "USB",
			"description": "USB",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 7,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		}
	]`

**Comment by florian-bogner** [comment]
i managed to get the 4 power outlets of my tuya power strip working as well as the usb outlet. unfortunately, the master switch does not work and i don't know how to figure out available/correct dps since i don't understand how to use the "journalctl -f -u homebridge" command.

here is the part of my config:

```
	"accessories": [
		{
			"accessory": "TuyaPowerStrip",
			"name": "Master?!",
			"description": "Master?",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 0,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Subwoofer",
			"description": "Subwoofer",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 1,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Drucker",
			"description": "Drucker",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 2,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "Lüfter",
			"description": "Lüfter",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 3,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "TV",
			"description": "TV",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 4,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		},
		{
			"accessory": "TuyaPowerStrip",
			"name": "USB",
			"description": "USB",
			"ip": "192.168.178.200",
			"devId": "17007751600194afc8de",
			"localKey": "d2c2512966953903",
			"dps": 7,
			"apiMinTimeout": 100,
			"apiMaxTimeout": 1000,
			"apiRetries": 1,
			"apiDebug": false,
			"refreshInterval": 120,
			"debugPrefix": "~~~!~~~ ",
			"debug": true,
			"superDebug": true,
			"deviceEnabled": true
		}
	]

```
it would be wonderful if you could have a look and maybe help me with "journalctl -f -u homebridge" and figuring out the dps numbers. thank you in advance :)
